apiVersion: v1
kind: ConfigMap
metadata:
 name: producer-envoy-config
 namespace: default
data:
 envoy.yaml: |-
   node:
     id: "publisher"
     cluster: "Participant-B"
   static_resources:
     listeners:
     - address:
         socket_address:
           address: 127.0.0.1
           port_value: 19092
       filter_chains:
       - filters:
         - name: envoy.filters.network.kafka_broker
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
             stat_prefix: exampleprefix
         - name: envoy.filters.network.tcp_proxy
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
             stat_prefix: tcp
             cluster: remotekafka           
     - address:
         socket_address:
           address: 127.0.0.1
           port_value: 19093
       filter_chains:
       - filters:
         - name: envoy.filters.network.kafka_broker
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
             stat_prefix: exampleprefix
         - name: envoy.filters.network.tcp_proxy
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
             stat_prefix: tcp
             cluster: plainkafka           
     clusters:
     - name: spire_agent
       connect_timeout: 0.25s
       http2_protocol_options: {} # Require HTTP2 communication
       hosts:
         - pipe:
             path: /run/spire/sockets/agent.sock
     - name: plainkafka
       connect_timeout: 0.25s
       type: strict_dns
       lb_policy: round_robin
       hosts:
       - socket_address:
           address: 20.79.115.224
           port_value: 9003
     - name: remotekafka
       connect_timeout: 0.25s
       type: strict_dns
       lb_policy: round_robin
       hosts:
       - socket_address:
           address: 20.79.115.224
           port_value: 9002
       tls_context:
         common_tls_context:
           tls_certificate_sds_secret_configs:
             - name: "spiffe://partb.org/kafka-demo/publisher"
               sds_config:
                 api_config_source:
                   api_type: GRPC
                   grpc_services:
                     envoy_grpc:
                       cluster_name: spire_agent
           combined_validation_context:
             # validate the SPIFFE ID of the server (recommended)
             default_validation_context:
               match_subject_alt_names:
                 exact: "spiffe://parta.org/kafka-demo/remote-broker"
             validation_context_sds_secret_config:
               name: spiffe://parta.org
               sds_config:
                 api_config_source:
                   api_type: GRPC
                   grpc_services:
                     envoy_grpc:
                       cluster_name: spire_agent
           tls_params:
             ecdh_curves:
               - X25519:P-256:P-521:P-384
   admin:
     access_log_path: /tmp/admin_access.log
     address:
       socket_address:
         address: 0.0.0.0
         port_value: 9901
#   dynamic_resources:
#     lds_config:
#       resource_api_version: V3
#       api_config_source:
#         api_type: GRPC
#         transport_api_version: V3
#         grpc_services:
#           - envoy_grpc:
#               cluster_name: remotekafka
#     cds_config:
#       resource_api_version: V3
#       api_config_source:
#         api_type: GRPC
#         transport_api_version: V3
#         grpc_services:
#           - envoy_grpc:
#               cluster_name: remotekafka
