apiVersion: v1
kind: Service
metadata:
  name: subscriber
spec:
  ports:
   - port: 19092
     name: http
     protocol: TCP
     targetPort: 19092
  selector:
      app: subscriber
  type: LoadBalancer
