# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  envoy.yaml: |-
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }

    node:
      id: "kafka"
      cluster: "Participant-A"

    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0 # Host that Kafka clients should connect to.
            port_value: 9003  # Port that Kafka clients should connect to.
        filter_chains:
        - filters:
          - name: envoy.filters.network.kafka_broker
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
              stat_prefix: exampleprefix
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: localkafka
      - address:
          socket_address:
            address: 0.0.0.0 # Host that Kafka clients should connect to.
            port_value: 9002  # Port that Kafka clients should connect to.
        filter_chains:
        - filters:
          - name: envoy.filters.network.kafka_broker
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
              stat_prefix: exampleprefix
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: localkafka
          tls_context:
            common_tls_context:
              tls_certificate_sds_secret_configs:
              - name: "spiffe://parta.org/kafka-demo/remote-broker"
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                      envoy_grpc:
                        cluster_name: spire_agent
              combined_validation_context:
                # validate the SPIFFE ID of incoming clients (optionally)
                default_validation_context:
                  verify_subject_alt_name:
                  - spiffe://partb.org/kafka-demo/publisher
                # obtain the trust bundle from SDS
                validation_context_sds_secret_config:
                  name: "spiffe://partb.org"
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
              tls_params:
                ecdh_curves:
                  - X25519:P-256:P-521:P-384
      - address:
          socket_address:
            address: 0.0.0.0 # Host that Kafka clients should connect to.
            port_value: 9001  # Port that Kafka clients should connect to.
        filter_chains:
        - filters:
          - name: envoy.filters.network.kafka_broker
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
              stat_prefix: exampleprefix
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: localkafka
          tls_context:
            common_tls_context:
              tls_certificate_sds_secret_configs:
              - name: "spiffe://parta.org/kafka-demo/broker"
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                      envoy_grpc:
                        cluster_name: spire_agent
              combined_validation_context:
                # validate the SPIFFE ID of incoming clients (optionally)
                default_validation_context:
                  verify_subject_alt_name:
                  - spiffe://parta.org/kafka-demo/publisher
                  - spiffe://parta.org/kafka-demo/subscriber
                # obtain the trust bundle from SDS
                validation_context_sds_secret_config:
                  name: "spiffe://parta.org"
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
              tls_params:
                ecdh_curves:
                  - X25519:P-256:P-521:P-384
      clusters:
      - name: spire_agent
        connect_timeout: 0.25s
        http2_protocol_options: {} # Require HTTP2 communication
        hosts:
          - pipe:
              path: /run/spire/sockets/agent.sock
      - name: localkafka
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: some_service
          endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1 # Kafka broker's host
                      port_value: 9092 # Kafka broker's port.
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"envoy.yaml":"admin:\n  access_log_path: /tmp/admin_access.log\n  address:\n    socket_address: { address: 0.0.0.0, port_value: 9901 }\n\nstatic_resources:\n  listeners:\n  - address:\n      socket_address:\n        address: 127.0.0.1 # Host that Kafka clients should connect to.\n        port_value: 19092  # Port that Kafka clients should connect to.\n    filter_chains:\n    - filters:\n      - name: envoy.filters.network.kafka_broker\n        typed_config:\n          \"@type\": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker\n          stat_prefix: exampleprefix\n      - name: envoy.filters.network.tcp_proxy\n        typed_config:\n          \"@type\": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\n          stat_prefix: tcp\n          cluster: localkafka\n  clusters:\n  - name: localkafka\n    connect_timeout: 0.25s\n    type: strict_dns\n    lb_policy: round_robin\n    load_assignment:\n      cluster_name: some_service\n      endpoints:\n        - lb_endpoints:\n          - endpoint:\n              address:\n                socket_address:\n                  address: 127.0.0.1 # Kafka broker's host\n                  port_value: 9092 # Kafka broker's port."},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"kafka","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kafka","helm.sh/chart":"kafka-11.8.1"},"name":"configmap-envoy","namespace":"default"}}
  labels:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-11.8.1
  name: configmap-envoy
  namespace: default
