kind: Service
apiVersion: v1
metadata:
  name: kafka
  namespace: default
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
spec:
  ports:
    - name: tcp-client
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: fed-client
      protocol: TCP
      port: 9002
      targetPort: 9002
    - name: remote-client
      protocol: TCP
      port: 9003
      targetPort: 9003
    - name: tcp-broker
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-headless
  namespace: default
  selfLink: /api/v1/namespaces/default/services/kafka-headless
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-11.8.1
spec:
  ports:
    - name: tcp-client
      protocol: TCP
      port: 9092
      targetPort: kafka-client
    - name: tcp-internal
      protocol: TCP
      port: 9093
      targetPort: kafka-internal
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  clusterIP: None
  type: ClusterIP
