kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: default
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: zookeeper
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-5.21.5
    role: zookeeper
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: zookeeper
      app.kubernetes.io/instance: zookeeper
      app.kubernetes.io/name: zookeeper
  template:
    metadata:
      name: zookeeper
      labels:
        app.kubernetes.io/component: zookeeper
        app.kubernetes.io/instance: zookeeper
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: zookeeper
        helm.sh/chart: zookeeper-5.21.5
    spec:
      containers:
        - name: zookeeper
          image: 'docker.io/bitnami/zookeeper:3.7.0'
          command:
            - bash
            - '-ec'
            - >
              # Execute entrypoint as usual after obtaining ZOO_SERVER_ID based
              on POD hostname

              HOSTNAME=`hostname -s`

              if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
                ORD=${BASH_REMATCH[2]}
                export ZOO_SERVER_ID=$((ORD+1))
              else
                echo "Failed to get index from hostname $HOST"
                exit 1
              fi

              exec /entrypoint.sh /run.sh
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: follower
              containerPort: 2888
              protocol: TCP
            - name: election
              containerPort: 3888
              protocol: TCP
          env:
            - name: ZOO_DATA_LOG_DIR
            - name: ZOO_PORT_NUMBER
              value: '2181'
            - name: ZOO_TICK_TIME
              value: '2000'
            - name: ZOO_INIT_LIMIT
              value: '10'
            - name: ZOO_SYNC_LIMIT
              value: '5'
            - name: ZOO_MAX_CLIENT_CNXNS
              value: '60'
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: 'srvr, mntr, ruok'
            - name: ZOO_LISTEN_ALLIPS_ENABLED
              value: 'no'
            - name: ZOO_AUTOPURGE_INTERVAL
              value: '0'
            - name: ZOO_AUTOPURGE_RETAIN_COUNT
              value: '3'
            - name: ZOO_MAX_SESSION_TIMEOUT
              value: '40000'
            - name: ZOO_SERVERS
              value: >-
                zookeeper-0.zookeeper-headless.default.svc.cluster.local:2888:3888
                zookeeper-1.zookeeper-headless.default.svc.cluster.local:2888:3888
                zookeeper-2.zookeeper-headless.default.svc.cluster.local:2888:3888
            - name: ZOO_ENABLE_AUTH
              value: 'no'
            - name: ZOO_HEAP_SIZE
              value: '1024'
            - name: ZOO_LOG_LEVEL
              value: ERROR
            - name: ALLOW_ANONYMOUS_LOGIN
              value: 'yes'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1001
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - metadata:
        name: data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: zookeeper-headless
  podManagementPolicy: Parallel
