kind: Service
apiVersion: v1
metadata:
  name: zookeeper
  namespace: default
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: zookeeper
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-5.21.5
spec:
  ports:
    - name: tcp-client
      protocol: TCP
      port: 2181
      targetPort: client
    - name: follower
      protocol: TCP
      port: 2888
      targetPort: follower
    - name: tcp-election
      protocol: TCP
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: zookeeper
    app.kubernetes.io/name: zookeeper
  type: ClusterIP
  sessionAffinity: None
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper-headless
  namespace: default
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: zookeeper
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-5.21.5
spec:
  ports:
    - name: tcp-client
      protocol: TCP
      port: 2181
      targetPort: client
    - name: follower
      protocol: TCP
      port: 2888
      targetPort: follower
    - name: tcp-election
      protocol: TCP
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: zookeeper
    app.kubernetes.io/name: zookeeper
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
